
# collection of small functions used in study:

# FOR TREE ANALYSIS: 
# supportive functions

dist_mtx_order = function(d, x){
  # Ordering distance matrixes
  # d = distance matrix (dist class)
  # x = vector to order dist. obj. by
  m = d %>% as.matrix
  d = as.dist(m[x,x])
  return(d)
}


## calculate patristic distance matrices for host tree

rescale_dist_mtx = function(m){
  m = m %>% as.matrix
  labs = m %>% colnames
  n_row = m %>% nrow
  n_col = m %>% ncol
  x = m %>% as.vector 
  x = scales::rescale(x)  # Rescale continuous vector to have specified minimum and maximum.
  m = matrix(x, nrow=n_row, ncol=n_col)
  colnames(m) = labs
  rownames(m) = labs
  m = m %>% as.dist
  return(m)
}


# Functions

#' randomly selecting one per group
#' L : list of distance matrixes used for MRM
#' df_grps : data.frame (sample, group)
one_per_group = function(L, df_grps, ...){
  # get subsample
  colnames(df_grps) = c('Sample', 'Group')
  df_grps = df_grps %>%
    group_by(Group) %>%
    sample_n(1)
  # subsetting all matrices
  lapply(L, function(x) dist_mtx_order(x, df_grps$Sample))
}

#' MRM on one subsample rep
#' i : rep number
#' L : list of list of distance matrices generated by `one_per_group()`
# nperm : nperm function for MRM
# f : MRM fomulat
mrm_each = function(i, L, f, nperm=99){
  m = L[[i]]
  f = as.formula(f)
  x = ecodist::MRM(f, nperm=nperm, mrank=TRUE) # note set to use Spearman correlation
  # coefficients
  df = x$coef %>% as.data.frame
  colnames(df) = c('coef', 'coef_pval')
  df$variable = rownames(df)
  df$R2 = x$r.squared[1]
  df$pval = x$r.squared[2]
  df$F = x$F.test[1]
  df$rep = i
  return(df)
}
